---

computername: dbg-macos-client
hostname: macbook-pro

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: yes
screensaver_ask_for_password_in_seconds: 3
keyboard_repeat_rate_in_seconds:  10
keyboard_repeat_delay_in_mseconds: 1
shell_path: /bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - aws/tap

homebrew_apps:
  - aerial
  - alfred
  - bartender
  - google-chrome
  - docker
  - fantastical
  - font-roboto
  - firefox
  - google-cloud-sdk
  - java
  - macpass
  - minikube
  - gpg-suite
  - iterm2
  - itsycal
  - skype
  - spectacle
  - virtualbox
  - visual-studio-code
  - vlc

homebrew_packages:
  - ansible
  - aws-shell
  - awscli
  - aws-sam-cli
  - azure-cli
  - bash
  - bash-completion
  - chag
  - calibre
  - composer
  - consul
  - coreutils
  - curl
  - go
  - google-cloud-sdk
  - git
  - httpie
  - inetutils
  - jq
  - kubernetes-cli
  - kubernetes-helm
  - {name: make, install_options: "with-default-names" }
  - minikube
  - nomad
  - node
  - packer
  - pkg-config
  - prometheus
  - python
  - terraform
  - unrar
  - vault
  - wget
  - zoom
  - zlib
  - zsh

mas_apps:
  - { name: Transmit, id: 1436522307 }
  - { name: Microsoft-remote-desktop, id: 1295203466 }
  - { name: CommanderOne, id: 1035236694 }
  - { name: MKPlayer, id: 1335612105 }
  - { name: XCode, id: 497799835 }
  - { name: Slack, id: 803453959 }
  - { name: TextWrangler, id: 404010395 }
  - { name: Unarchiver, id: 425424353 }
